### ISSUE TITLE
pieusb: I/O Error on SLIDE_LAMP_ON command on ProScan10T 05e3:0145 model number 71

### ISSUE THREAD

**Issue by mmuman** [kkaempf/sane-backends#10]
A friend brought a ProScan10T at [JDLL](http://www.jdll.org/) yesterday and asked for help to make it work.

We did some tests with logging on the pieusb backend, first 1.0.25, 1.0.26, then the git HEAD, and it always failed when trying to set the lamp on, while the lamp is actually always on from the machine start-up. Maybe they wanted to spare a transistor...

Commenting the SLIDE_LAMP_ON command as such makes it scan correctly:

```diff
diff --git a/backend/pieusb.c b/backend/pieusb.c
index 4b073040..09e7eff7 100644
--- a/backend/pieusb.c
+++ b/backend/pieusb.c
@@ -1042,6 +1042,7 @@ sane_start (SANE_Handle handle)
      * Lamp on
      *
      * ---------------------------------------------------------------------- */
+/*
     sanei_pieusb_cmd_slide (scanner->device_number, SLIDE_LAMP_ON, &status);
     if (status.pieusb_status != PIEUSB_STATUS_GOOD) {
       DBG (DBG_error, "sane_start(): sanei_pieusb_cmd_slide failed: %d\n", status.pieusb_status);
@@ -1052,6 +1053,7 @@ sane_start (SANE_Handle handle)
       DBG (DBG_error, "sane_start: scanner not ready %d\n", st);
       return st;
     }
+*/
 
     /* Enter SCAN phase 1 */
     DBG (DBG_info_sane, "sane_start(): scan phase 1\n");
```

Attached the failed scanimage -T log:
[scanimage_proscan10t_bad.txt](https://github.com/kkaempf/sane-backends/files/888429/scanimage_proscan10t_bad.txt)
And the log with the LAMP_ON command commented:
[scanimage_proscan10t.txt](https://github.com/kkaempf/sane-backends/files/888430/scanimage_proscan10t.txt)

Maybe it should be possible to detect if the lamp is switchable or not in some way?
I won't have access to the hardware anymore though, I suggest we at least add a test on the version, or maybe just not fail in case of error there but just output a warning so it wouldn't prevent scanning.

**Comment by kkaempf** [comment]
Please try the "kkaempf" branch.

**Comment by mmuman** [comment]
I'll have him try it, but he's not used to git and I only have mail to guide him...

**Comment by kkaempf** [comment]
I pushed this to upstream now and it will be part of the upcoming salt-backends-1.0.26 release
