### ISSUE TITLE
fig2dev and dlh not handled in the configure

### ISSUE THREAD

**Issue by iwkse** [kkaempf/sane-backends#6]
While trying to build sane backends, I got these errors which are not easy to catch. Right now if the binaries are not available you get

FIG2DEV = no
and
DLH = no

I'm still trying to figure out, on my system (debian), where the dlh binary is.

Please make this check part of configure

**Comment by kkaempf** [comment]
Sorry, you're "barking up the wrong tree". sane-backends is hosted on `git.debian.org`
