### ISSUE TITLE
Canon CanoScan Lide 120: Bulb won't power on; all images are a grey blob

### ISSUE THREAD

**Issue by Dev0Null** [kkaempf/sane-backends#8]
I've just tested by re-building `sane-backends` from scratch and deploying on an Ubuntu 16.04.1 LTS machine (x64). All images generated by "Simple Scan" and "XSane Image Processing Program" are uniform gray images with no distinguishing features. I've iterated through most DPI/bit-depth settings, and the results are the same.

When a scan starts up, I hear a brief bit of noise from the motor, and for about 30 seconds, I see near the front of the scanner (ie: near the tactile buttons/switches, opposite of the "hinged" side), what appears to be the scanner bulb attempting to turn on, but just flickers a bit instead.

I've tested with direct connections between the scanner and rear USB ports on my machine, with cables ranging in length from 6" to 3', have tried powered USB hubs, and even a [USB dual power/data cable]( https://sgcdn.startech.com/005329/media/products/gallery_large/USB2HABMYX.Main.jpg); all resulting in the same failure.

I'm able to use any of the mentioned cables/setups above with the same machine when I boot into Windows 7, so I suspect it's a s/w rather than a h/w or power issue.

**Comment by kkaempf** [comment]
Sorry, you're "barking up the wrong tree". sane-backends is hosted on `git.debian.org`

**Comment by Dev0Null** [comment]
A mistake on my part: I meant to say that I built the code hosted at this project page (`kkaempf/sane-backends`), rather than "`sane-backends`".
