### ISSUE TITLE
Pixma-bjnp: Select timeout on network scan

### ISSUE THREAD

**Issue by pixmaDebug** [kkaempf/sane-backends#9]
Hi, I think I found an issue on network scanning with a Pixma MG5750 (using simple-scan) :
- start a network scan: works
- start a second network-scan on the same device: produces the following error in the shell:
```
[bjnp] bjnp_recv_data: ERROR - could not read response payload (select timed out)!
[bjnp] bjnp_write: ERROR - scanner data left = 0x1a4c = 6732
[bjnp] bjnp_recv_header: ERROR - could not read response header (select timed out)!
[bjnp] sanei_bjnp_write_bulk: ERROR - Could not read response to command!
[bjnp] bjnp_write: ERROR - scanner data left = 0x1a4c = 6732
[bjnp] bjnp_recv_header: ERROR - could not read response header (select timed out)!
[bjnp] sanei_bjnp_write_bulk: ERROR - Could not read response to command!
```
In /etc/sane.d/pixma.conf I do have
`bjnp://192.168.1.110`
which is the right IP to the scanner...

So according to the error, and after a quick `man select` I think this might be the cause:
```
       The operation of select() and pselect() is identical, other than
       these three differences:

       (i)    select() uses a timeout that is a struct timeval (with seconds
              and microseconds), while pselect() uses a struct timespec
              (with seconds and nanoseconds).

       (ii)   select() may update the timeout argument to indicate how much
              time was left.  pselect() does not change this argument.
```

For further details about this:
- http://man7.org/linux/man-pages/man2/select.2.html
- http://stackoverflow.com/questions/4407012/is-timeout-changed-after-a-call-to-select-in-c
- http://stackoverflow.com/questions/3324078/why-select-always-return-0-after-the-first-timeout

It might be better to use poll() or pselect() instead of select()... Though I don't know which would be the implications on the rest of the code. 

And if not, then the timeout value should be resetted after each use to something big so that network scans don't get interrupted in the middle after the first one...

I hope this is a real issue and other can reproduce, I could test an updated version of this if needed.

Thanks for the great work anyway, when it works, it really does ;-}

Have a good day !

**Comment by llagendijk** [comment]
Before you dig in the code: did you open the firewall ports as described in man sane-pixma? I have seen the select time-outs only when really nothing was received or there were other errors (e.g. errors in the back end itself). Ans the code accounts for the fact that select changes the time-out value, so it is unlikely that this causes the issues. And I should know: I wrote the code, but that was years ago....

**Comment by pixmaDebug** [comment]
Hi, thanks for answering so quickly !

Also thanks for pointing me out to the man sane-pixma, I missed this one in my investigations ;-}

Still, the firewall is wide open on the laptop and the scanner is on the same WLAN with no filtering in place. Sometimes the problem occurs before anything is actually displayed in simple-scan, and sometimes it happens after some of the image is displayed.

But I have definitely no problem for communicating with the scanner and receiving traffic from it (I actually sent, using  'nc -u', raw binary packets extracted from a dump I made to verify that in the first place, and it works like a charm).

Basically, the less quality I choose, the more data I get, but as soon as I encounter the issue, the scanner hangs and I have to : 
  - press the power button to shut it down, and back on
             OR
  - switch back to USB (see 
[pixma.debug.usb_after_net.txt](https://github.com/kkaempf/sane-backends/files/835926/pixma.debug.usb_after_net.txt))

I found the debugging environment variables thanks to you, so I could dump everything for comparing what happens when using USB vs Net, so I'll put the debug-log here to... We'll see if it helps ;-}

[pixma.debug.usb.txt](https://github.com/kkaempf/sane-backends/files/835918/pixma.debug.usb.txt)
[pixma.debug.net.txt](https://github.com/kkaempf/sane-backends/files/835917/pixma.debug.net.txt)

And the main reason I dug into the code was to find a way to increase the initial timeout passed to select() to a somewhat insane value, to see if it changes anything... If you have an idea how I could test that, is it somewhere at the kernel level maybe ?

Dank u well again, hope to solve this soon, also if you want I can test basically any version of any scanning-software from every distro using docker ;-}

Have a nice day !

**Comment by llagendijk** [comment]
On Sat, 2017-03-11 at 08:12 -0800, pixmaDebug wrote:
> Hi, thanks for answering so quickly !
> 
> Also thanks for pointing me out to the man sane-pixma, I missed this
> one in my investigations ;-}
> 
> Still, the firewall is wide open on the laptop and the scanner is on
> the same WLAN with no filtering in place. Sometimes the problem
> occurs before anything is actually displayed in simple-scan, and
> sometimes it happens after some of the image is displayed.
> 
> But I have definitely no problem for communicating with the scanner
> and receiving traffic from it (I actually sent, using  'nc -u', raw
> binary packets extracted from a dump I made to verify that in the
> first place, and it works like a charm).
> 
> Basically, the less quality I choose, the more data I get, but as
> soon as I encounter the issue, the scanner hangs and I have to :
> 
> 
> press the power button to shut it down, and back on
> 
> OR
> switch back to USB (see
> 
> pixma.debug.usb_after_net.txt)
> 
> I found the debugging environment variables thanks to you, so I could
> dump everything for comparing what happens when using USB vs Net, so
> I'll put the debug-log here to... We'll see if it helps ;-}
> 
> pixma.debug.usb.txt
> 
> pixma.debug.net.txt
> 
> And the main reason I dug into the code was to find a way to increase
> the initial timeout passed to select() to a somewhat insane value, to
> see if it changes anything... If you have an idea how I could test
> that, is it somewhere at the kernel level maybe ?
> 
> Dank u well again, hope to solve this soon, also if you want I can
> test basically any version of any scanning-software from every distro
> using docker ;-}
> 
> Have a nice day !
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/kkaempf/s
> ane-backends","title":"kkaempf/sane-backends","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/kkaempf/sane-
> backends"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pixma
> Debug in #9: Hi, thanks for answering so quickly !\r\n\r\nAlso thanks
> for pointing me out to the man sane-pixma, I missed this one in my
> investigations ;-}\r\n\r\nStill, the firewall is wide open on the
> laptop and the scanner is on the same WLAN with no filtering in
> place. Sometimes the problem occurs before anything is actually
> displayed in simple-scan, and sometimes it happens after some of the
> image is displayed.\r\n\r\nBut I have definitely no problem for
> communicating with the scanner and receiving traffic from it (I
> actually sent, using  'nc -u', raw binary packets extracted from a
> dump I made to verify that in the first place, and it works like a
> charm).\r\n\r\nBasically, the less quality I choose, the more data I
> get, but as soon as I encounter the issue, the scanner hangs and I
> have to : \r\n  - press the power button to shut it down, and back
> on\r\n             OR\r\n  - switch back to USB (see
> \r\n[pixma.debug.usb_after_net.txt](https://github.com/kkaempf/sane-b
> ackends/files/835926/pixma.debug.usb_after_net.txt))\r\n\r\nI found
> the debugging environment variables thanks to you, so I could dump
> everything for comparing what happens when using USB vs Net, so I'll
> put the debug-log here to... We'll see if it helps ;-
> }\r\n\r\n[pixma.debug.usb.txt](https://github.com/kkaempf/sane-
> backends/files/835918/pixma.debug.usb.txt)\r\n[pixma.debug.net.txt](h
> ttps://github.com/kkaempf/sane-
> backends/files/835917/pixma.debug.net.txt)\r\n\r\nAnd the main reason
> I dug into the code was to find a way to increase the initial timeout
> passed to select() to a somewhat insane value, to see if it changes
> anything... If you have an idea how I could test that, is it
> somewhere at the kernel level maybe ?\r\n\r\nDank u well again, hope
> to solve this soon, also if you want I can test basically any version
> of any scanning-software from every distro using docker ;-
> }\r\n\r\nHave a nice day !\r\n\r\n\r\n"}],"action":{"name":"View
> Issue","url":"https://github.com/kkaempf/sane-
> backends/issues/9#issuecomment-285877898"}}}
Next question then: what version of the sane-backends are you using? In
the latest version  ofv git I added some code (quitr recently) that
allows you to set the timeout on either global or per scanner in the
pixma.conf:
# pixma.conf configuration for the sane pixma backend
#
# bjnp-timeout=5000
# Specify the timeout (in ms) to be used for all the folllowing
# scanners.
# May be specified multiple times.
# The last value (if any) will be used for auto-detection
#
# define URI's of scanners (one per line)
# This is only used for network scanners.
# normally scanners will be detected by sending a broadcast
# if this does not work under your OS, or if the scanners
# are on a different subnet, configure your scanners URI here
#
# method must be bjnp
# port number can normally be left out, port 8612 is used as default
# The timeout parameter sets a timeout value for the scanner on
# the same line
# Example:
# bjnp://myscanner.my.domain:8612 // uses the default 1000ms timeout
# bjnp-timeout=5000
# bjnp://printer-1.pheasant.org // will use the 5000 ms timeout
# bjnp://scanner.bad-network.org/timeout=1500 // timeout set to 1500 ms
# bjnp-timeout=3000 // will be used for auto-detected scanners
#
It is documented in sane-pixma  as well I think

BR, Louis

**Comment by pixmaDebug** [comment]
Ah ok, this explains a lot. I couldn't find a reference to 'timeout' in man sane-pixma though, except the one about button-scan.

The version I'm using:

**Comment by llagendijk** [comment]
Hi
Your sane snapshot is too old to contain the timeout patch: that was added in git on January 6. So you need to find a newer sane package or compile from source.
When it still doe not work wiith a recent enough sane version, please get me the output from a scanimage with SANE_DEBUG_BJNP set to 11.

**Comment by pixmaDebug** [comment]
Hi, sorry I had a busy week, couldn't test anything until now.

I downloaded `sane-backends-git20170323.tgz` and built it with `--enable-avahi` .
I confirm that this is working better, still some problems on bigger resolutions, but I can live with that.

For completeness, here are my tests using the snapshot git20170323 :
- bjnp-timeout=9999 res=300ppp => scan successful
- bjnp-timeout=9999 res=600ppp => scan successful
- bjnp-timeout=9999 res=1200ppp => ERROR - could not read response payload (select timed out)
- bjnp-timeout=20000 res=1200ppp => ERROR - could not read response payload (select timed out)
- bjnp-timeout=9999 res=2400ppp => ERROR - could not read response payload (select timed out)
- bjnp-timeout=20000 res=2400ppp => ERROR - could not read response payload (select timed out)

If I can help solve these, I'll be happy to do so !

Thanks anyway

**Comment by kkaempf** [comment]
Sorry guys, you're "barking up the wrong tree". sane-backends is hosted on `git.debian.org`

**Comment by llagendijk** [comment]
hi Pixmadebug,
Please get me a logfile of a succesful and a failed scan:
export SANE_DEBUG_BJNP=4
scanimage --resolution=1200 > bjnp_log
to louis.lagendijk@gmail.com and let's continue the discussion on the sane mailinglist

**Comment by hemenkapadia** [comment]
Was a solution found to this issue? I am facing the exact same error.

- The laptop and Scanner are on the same wifi connection. There is no firewall issue as I have been able to successfully scan images on this setup. 
- However, for about 80% of scans I keep getting this error, then need to retry and after some time it works for the entire image (basically I need to get lucky)


```
[+50.06s] DEBUG: scanner.vala:1321: sane_read (122497) -> (SANE_STATUS_GOOD, 76560)
[+50.06s] DEBUG: scanner.vala:1321: sane_read (122497) -> (SANE_STATUS_GOOD, 76560)
[+50.06s] DEBUG: scanner.vala:1321: sane_read (122497) -> (SANE_STATUS_GOOD, 38280)
[bjnp] bjnp_recv_header: ERROR - could not read response header (select timed out after 1000 ms)!
[bjnp] bjnp_recv_header: ERROR - Received response has serial 1654, expected 1655
[bjnp] bjnp_recv_header: ERROR - Received response has cmd code 236, expected 33
[bjnp] sanei_bjnp_write_bulk: ERROR - Could not read response to command!
[bjnp] bjnp_recv_header: ERROR - Received response has cmd code 232, expected 33
[bjnp] sanei_bjnp_write_bulk: ERROR - Could not read response to command!
[+51.51s] DEBUG: scanner.vala:1321: sane_read (122497) -> (SANE_STATUS_IO_ERROR, 0)
[+51.51s] WARNING: scanner.vala:1337: Unable to read frame from device: Error during device I/O
[+51.51s] DEBUG: scanner.vala:768: sane_cancel ()
[+51.51s] DEBUG: scanner.vala:771: sane_close ()
```

**Comment by llagendijk** [comment]
Please move this discussion to gitlab sane repository. https://gitlab.com/sane-project/backends
Anyhow, I guess that you are using an old sane version? 1.0,29 is current

**Comment by hemenkapadia** [comment]
Thanks, @llagendijk. My sane version is `1.0.27`. I am on Ubuntu 18.04 and frequently do `apt-get update && apt-get upgrade`. Possibly Ubuntu repos are not updated with latest sane version so there would be others like me.

Anyway, I was able to fix this issue, hence updating here just in case someone lands on this page.

On Ubuntu 18.04, edit `/etc/sane.d/pixma.conf` and add line `bjnp-timeout=10000` as the last line of the file. I have my scanner in auto-detect mode hence the last line.

Additional note from the file for others

```
# bjnp-timeout=5000
# Specify the timeout (in ms) to be used for all the folllowing scanners.
# May be specified multiple times.
# The last value (if any) will be used for auto-detection
```
